name: Build LaTeX PDF

on:
  push:
    paths:
      - '**/*.tex'
      - '**/*.bib'
      - '**/*.sty'
      - '.github/workflows/latex-build.yml'
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install TeX Live & latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            latexmk

      - name: Compile with latexmk
        run: |
          latexmk -pdf \
            -interaction=nonstopmode \
            -halt-on-error \
            main.tex

      - name: Commit built PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          if ! git diff --cached --quiet; then
            git commit -m "ci: rebuild PDF"
            git push
          else
            echo "No changes to PDF; skipping commit."
          fi
